import blockContent from './blockContent'
import category from './category'
import post from './post'
import author from './author'
import Header from './header'
import Footer from './footer'
import Page from './page'
import Section from './section'
import heroSection from './sections/heroSection'
import blogSection from './sections/blogSection'
import faqSection from './sections/faqSection'
import mainSection from './sections/mainSection'
import featureSection from './sections/offerSection'
import testimonialSection from './sections/testimonialSection'
export const schemaTypes = [post, author, category, blockContent,Header,Footer,Page,Section,heroSection,blogSection,faqSection,mainSection,featureSection,testimonialSection]
